#!/usr/bin/python

def startDbusInterface():
        from dbus.mainloop.glib import DBusGMainLoop
        from Yowsup.Interfaces.DBus.DBusInterface import DBusInitInterface
        import gobject
        
        DBusGMainLoop(set_as_default=True)
        
        DBusInitInterface()
        
        mainloop = gobject.MainLoop()
        
        gobject.threads_init()
        print("starting")
        mainloop.run()


startDbusInterface()
